name: DotNet Api Scan
schedules:
- cron: "0 7 * * *"
  displayName: Daily run
  branches:
    include:
    - dev

pool:
  vmImage: windows-2019

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: |
     packages/function-extension
    arguments: '/p:Configuration=Release'

# Remove files that won't be released
- task: APIScan@2
  displayName: 'Run APIScan'
  inputs:
    softwareFolder: 'packages/function-extension/src/bin/Release/netcoreapp3.1'
    softwareName: TeamsFxFunctionExtension
    softwareVersionNum: '$(Build.BuildId)'
    isLargeApp: false
    verbosityLevel: 'none'
  env:
    AzureServicesAuthConnectionString: '$(AzureServicesAuthConnectionString)'